/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_angiopasqui_permissionchecker_SSL */

#ifndef _Included_com_example_angiopasqui_permissionchecker_SSL
#define _Included_com_example_angiopasqui_permissionchecker_SSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_angiopasqui_permissionchecker_SSL
 * Method:    Sign
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_angiopasqui_permissionchecker_SSL_Sign
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
